// MusicPlayerPlatformDesign.v

// Generated using ACDS version 22.1 922

`timescale 1 ps / 1 ps
module MusicPlayerPlatformDesign (
		inout  wire       audio_config_export_SDAT,  // audio_config_export.SDAT
		output wire       audio_config_export_SCLK,  //                    .SCLK
		input  wire       audio_export_BCLK,         //        audio_export.BCLK
		output wire       audio_export_DACDAT,       //                    .DACDAT
		input  wire       audio_export_DACLRCK,      //                    .DACLRCK
		input  wire [3:0] buttons_input_export,      //       buttons_input.export
		input  wire       clk_clk,                   //                 clk.clk
		input  wire       reset_reset_n,             //               reset.reset_n
		input  wire       switch_input_export,       //        switch_input.export
		output wire [1:0] timer_ctrl_output_export,  //   timer_ctrl_output.export
		input  wire [1:0] timer_status_input_export, //  timer_status_input.export
		input  wire       vga_clk_clk,               //             vga_clk.clk
		output wire       vga_outputs_CLK,           //         vga_outputs.CLK
		output wire       vga_outputs_HS,            //                    .HS
		output wire       vga_outputs_VS,            //                    .VS
		output wire       vga_outputs_BLANK,         //                    .BLANK
		output wire       vga_outputs_SYNC,          //                    .SYNC
		output wire [7:0] vga_outputs_R,             //                    .R
		output wire [7:0] vga_outputs_G,             //                    .G
		output wire [7:0] vga_outputs_B              //                    .B
	);

	wire         vga_char_buffer_avalon_char_source_valid;                               // VGA_CHAR_BUFFER:stream_valid -> VGA_CONTROLLER:valid
	wire  [29:0] vga_char_buffer_avalon_char_source_data;                                // VGA_CHAR_BUFFER:stream_data -> VGA_CONTROLLER:data
	wire         vga_char_buffer_avalon_char_source_ready;                               // VGA_CONTROLLER:ready -> VGA_CHAR_BUFFER:stream_ready
	wire         vga_char_buffer_avalon_char_source_startofpacket;                       // VGA_CHAR_BUFFER:stream_startofpacket -> VGA_CONTROLLER:startofpacket
	wire         vga_char_buffer_avalon_char_source_endofpacket;                         // VGA_CHAR_BUFFER:stream_endofpacket -> VGA_CONTROLLER:endofpacket
	wire  [31:0] cpu_nios_ii_data_master_readdata;                                       // mm_interconnect_0:CPU_NIOS_II_data_master_readdata -> CPU_NIOS_II:d_readdata
	wire         cpu_nios_ii_data_master_waitrequest;                                    // mm_interconnect_0:CPU_NIOS_II_data_master_waitrequest -> CPU_NIOS_II:d_waitrequest
	wire         cpu_nios_ii_data_master_debugaccess;                                    // CPU_NIOS_II:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:CPU_NIOS_II_data_master_debugaccess
	wire  [19:0] cpu_nios_ii_data_master_address;                                        // CPU_NIOS_II:d_address -> mm_interconnect_0:CPU_NIOS_II_data_master_address
	wire   [3:0] cpu_nios_ii_data_master_byteenable;                                     // CPU_NIOS_II:d_byteenable -> mm_interconnect_0:CPU_NIOS_II_data_master_byteenable
	wire         cpu_nios_ii_data_master_read;                                           // CPU_NIOS_II:d_read -> mm_interconnect_0:CPU_NIOS_II_data_master_read
	wire         cpu_nios_ii_data_master_write;                                          // CPU_NIOS_II:d_write -> mm_interconnect_0:CPU_NIOS_II_data_master_write
	wire  [31:0] cpu_nios_ii_data_master_writedata;                                      // CPU_NIOS_II:d_writedata -> mm_interconnect_0:CPU_NIOS_II_data_master_writedata
	wire  [31:0] cpu_nios_ii_instruction_master_readdata;                                // mm_interconnect_0:CPU_NIOS_II_instruction_master_readdata -> CPU_NIOS_II:i_readdata
	wire         cpu_nios_ii_instruction_master_waitrequest;                             // mm_interconnect_0:CPU_NIOS_II_instruction_master_waitrequest -> CPU_NIOS_II:i_waitrequest
	wire  [19:0] cpu_nios_ii_instruction_master_address;                                 // CPU_NIOS_II:i_address -> mm_interconnect_0:CPU_NIOS_II_instruction_master_address
	wire         cpu_nios_ii_instruction_master_read;                                    // CPU_NIOS_II:i_read -> mm_interconnect_0:CPU_NIOS_II_instruction_master_read
	wire         mm_interconnect_0_audio_out_avalon_audio_slave_chipselect;              // mm_interconnect_0:AUDIO_OUT_avalon_audio_slave_chipselect -> AUDIO_OUT:chipselect
	wire  [31:0] mm_interconnect_0_audio_out_avalon_audio_slave_readdata;                // AUDIO_OUT:readdata -> mm_interconnect_0:AUDIO_OUT_avalon_audio_slave_readdata
	wire   [1:0] mm_interconnect_0_audio_out_avalon_audio_slave_address;                 // mm_interconnect_0:AUDIO_OUT_avalon_audio_slave_address -> AUDIO_OUT:address
	wire         mm_interconnect_0_audio_out_avalon_audio_slave_read;                    // mm_interconnect_0:AUDIO_OUT_avalon_audio_slave_read -> AUDIO_OUT:read
	wire         mm_interconnect_0_audio_out_avalon_audio_slave_write;                   // mm_interconnect_0:AUDIO_OUT_avalon_audio_slave_write -> AUDIO_OUT:write
	wire  [31:0] mm_interconnect_0_audio_out_avalon_audio_slave_writedata;               // mm_interconnect_0:AUDIO_OUT_avalon_audio_slave_writedata -> AUDIO_OUT:writedata
	wire  [31:0] mm_interconnect_0_audio_config_avalon_av_config_slave_readdata;         // AUDIO_CONFIG:readdata -> mm_interconnect_0:AUDIO_CONFIG_avalon_av_config_slave_readdata
	wire         mm_interconnect_0_audio_config_avalon_av_config_slave_waitrequest;      // AUDIO_CONFIG:waitrequest -> mm_interconnect_0:AUDIO_CONFIG_avalon_av_config_slave_waitrequest
	wire   [1:0] mm_interconnect_0_audio_config_avalon_av_config_slave_address;          // mm_interconnect_0:AUDIO_CONFIG_avalon_av_config_slave_address -> AUDIO_CONFIG:address
	wire         mm_interconnect_0_audio_config_avalon_av_config_slave_read;             // mm_interconnect_0:AUDIO_CONFIG_avalon_av_config_slave_read -> AUDIO_CONFIG:read
	wire   [3:0] mm_interconnect_0_audio_config_avalon_av_config_slave_byteenable;       // mm_interconnect_0:AUDIO_CONFIG_avalon_av_config_slave_byteenable -> AUDIO_CONFIG:byteenable
	wire         mm_interconnect_0_audio_config_avalon_av_config_slave_write;            // mm_interconnect_0:AUDIO_CONFIG_avalon_av_config_slave_write -> AUDIO_CONFIG:write
	wire  [31:0] mm_interconnect_0_audio_config_avalon_av_config_slave_writedata;        // mm_interconnect_0:AUDIO_CONFIG_avalon_av_config_slave_writedata -> AUDIO_CONFIG:writedata
	wire         mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_chipselect;  // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_chipselect -> VGA_CHAR_BUFFER:buf_chipselect
	wire   [7:0] mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_readdata;    // VGA_CHAR_BUFFER:buf_readdata -> mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_readdata
	wire         mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_waitrequest; // VGA_CHAR_BUFFER:buf_waitrequest -> mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_waitrequest
	wire  [12:0] mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_address;     // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_address -> VGA_CHAR_BUFFER:buf_address
	wire         mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_read;        // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_read -> VGA_CHAR_BUFFER:buf_read
	wire   [0:0] mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_byteenable;  // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_byteenable -> VGA_CHAR_BUFFER:buf_byteenable
	wire         mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_write;       // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_write -> VGA_CHAR_BUFFER:buf_write
	wire   [7:0] mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_writedata;   // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_buffer_slave_writedata -> VGA_CHAR_BUFFER:buf_writedata
	wire         mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_chipselect; // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_control_slave_chipselect -> VGA_CHAR_BUFFER:ctrl_chipselect
	wire  [31:0] mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_readdata;   // VGA_CHAR_BUFFER:ctrl_readdata -> mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_control_slave_readdata
	wire   [0:0] mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_address;    // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_control_slave_address -> VGA_CHAR_BUFFER:ctrl_address
	wire         mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_read;       // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_control_slave_read -> VGA_CHAR_BUFFER:ctrl_read
	wire   [3:0] mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_byteenable; // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_control_slave_byteenable -> VGA_CHAR_BUFFER:ctrl_byteenable
	wire         mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_write;      // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_control_slave_write -> VGA_CHAR_BUFFER:ctrl_write
	wire  [31:0] mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_writedata;  // mm_interconnect_0:VGA_CHAR_BUFFER_avalon_char_control_slave_writedata -> VGA_CHAR_BUFFER:ctrl_writedata
	wire         mm_interconnect_0_uart_nios_v_avalon_jtag_slave_chipselect;             // mm_interconnect_0:UART_NIOS_V_avalon_jtag_slave_chipselect -> UART_NIOS_V:av_chipselect
	wire  [31:0] mm_interconnect_0_uart_nios_v_avalon_jtag_slave_readdata;               // UART_NIOS_V:av_readdata -> mm_interconnect_0:UART_NIOS_V_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_uart_nios_v_avalon_jtag_slave_waitrequest;            // UART_NIOS_V:av_waitrequest -> mm_interconnect_0:UART_NIOS_V_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_uart_nios_v_avalon_jtag_slave_address;                // mm_interconnect_0:UART_NIOS_V_avalon_jtag_slave_address -> UART_NIOS_V:av_address
	wire         mm_interconnect_0_uart_nios_v_avalon_jtag_slave_read;                   // mm_interconnect_0:UART_NIOS_V_avalon_jtag_slave_read -> UART_NIOS_V:av_read_n
	wire         mm_interconnect_0_uart_nios_v_avalon_jtag_slave_write;                  // mm_interconnect_0:UART_NIOS_V_avalon_jtag_slave_write -> UART_NIOS_V:av_write_n
	wire  [31:0] mm_interconnect_0_uart_nios_v_avalon_jtag_slave_writedata;              // mm_interconnect_0:UART_NIOS_V_avalon_jtag_slave_writedata -> UART_NIOS_V:av_writedata
	wire  [31:0] mm_interconnect_0_cpu_nios_ii_debug_mem_slave_readdata;                 // CPU_NIOS_II:debug_mem_slave_readdata -> mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_readdata
	wire         mm_interconnect_0_cpu_nios_ii_debug_mem_slave_waitrequest;              // CPU_NIOS_II:debug_mem_slave_waitrequest -> mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_cpu_nios_ii_debug_mem_slave_debugaccess;              // mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_debugaccess -> CPU_NIOS_II:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_cpu_nios_ii_debug_mem_slave_address;                  // mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_address -> CPU_NIOS_II:debug_mem_slave_address
	wire         mm_interconnect_0_cpu_nios_ii_debug_mem_slave_read;                     // mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_read -> CPU_NIOS_II:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_cpu_nios_ii_debug_mem_slave_byteenable;               // mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_byteenable -> CPU_NIOS_II:debug_mem_slave_byteenable
	wire         mm_interconnect_0_cpu_nios_ii_debug_mem_slave_write;                    // mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_write -> CPU_NIOS_II:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_cpu_nios_ii_debug_mem_slave_writedata;                // mm_interconnect_0:CPU_NIOS_II_debug_mem_slave_writedata -> CPU_NIOS_II:debug_mem_slave_writedata
	wire         mm_interconnect_0_ram_nios_v_s1_chipselect;                             // mm_interconnect_0:RAM_NIOS_V_s1_chipselect -> RAM_NIOS_V:chipselect
	wire  [31:0] mm_interconnect_0_ram_nios_v_s1_readdata;                               // RAM_NIOS_V:readdata -> mm_interconnect_0:RAM_NIOS_V_s1_readdata
	wire  [15:0] mm_interconnect_0_ram_nios_v_s1_address;                                // mm_interconnect_0:RAM_NIOS_V_s1_address -> RAM_NIOS_V:address
	wire   [3:0] mm_interconnect_0_ram_nios_v_s1_byteenable;                             // mm_interconnect_0:RAM_NIOS_V_s1_byteenable -> RAM_NIOS_V:byteenable
	wire         mm_interconnect_0_ram_nios_v_s1_write;                                  // mm_interconnect_0:RAM_NIOS_V_s1_write -> RAM_NIOS_V:write
	wire  [31:0] mm_interconnect_0_ram_nios_v_s1_writedata;                              // mm_interconnect_0:RAM_NIOS_V_s1_writedata -> RAM_NIOS_V:writedata
	wire         mm_interconnect_0_ram_nios_v_s1_clken;                                  // mm_interconnect_0:RAM_NIOS_V_s1_clken -> RAM_NIOS_V:clken
	wire         mm_interconnect_0_reg_btn_input_s1_chipselect;                          // mm_interconnect_0:REG_BTN_INPUT_s1_chipselect -> REG_BTN_INPUT:chipselect
	wire  [31:0] mm_interconnect_0_reg_btn_input_s1_readdata;                            // REG_BTN_INPUT:readdata -> mm_interconnect_0:REG_BTN_INPUT_s1_readdata
	wire   [1:0] mm_interconnect_0_reg_btn_input_s1_address;                             // mm_interconnect_0:REG_BTN_INPUT_s1_address -> REG_BTN_INPUT:address
	wire         mm_interconnect_0_reg_btn_input_s1_write;                               // mm_interconnect_0:REG_BTN_INPUT_s1_write -> REG_BTN_INPUT:write_n
	wire  [31:0] mm_interconnect_0_reg_btn_input_s1_writedata;                           // mm_interconnect_0:REG_BTN_INPUT_s1_writedata -> REG_BTN_INPUT:writedata
	wire         mm_interconnect_0_reg_sw_input_s1_chipselect;                           // mm_interconnect_0:REG_SW_INPUT_s1_chipselect -> REG_SW_INPUT:chipselect
	wire  [31:0] mm_interconnect_0_reg_sw_input_s1_readdata;                             // REG_SW_INPUT:readdata -> mm_interconnect_0:REG_SW_INPUT_s1_readdata
	wire   [1:0] mm_interconnect_0_reg_sw_input_s1_address;                              // mm_interconnect_0:REG_SW_INPUT_s1_address -> REG_SW_INPUT:address
	wire         mm_interconnect_0_reg_sw_input_s1_write;                                // mm_interconnect_0:REG_SW_INPUT_s1_write -> REG_SW_INPUT:write_n
	wire  [31:0] mm_interconnect_0_reg_sw_input_s1_writedata;                            // mm_interconnect_0:REG_SW_INPUT_s1_writedata -> REG_SW_INPUT:writedata
	wire  [31:0] mm_interconnect_0_timer_status_input_s1_readdata;                       // TIMER_STATUS_INPUT:readdata -> mm_interconnect_0:TIMER_STATUS_INPUT_s1_readdata
	wire   [1:0] mm_interconnect_0_timer_status_input_s1_address;                        // mm_interconnect_0:TIMER_STATUS_INPUT_s1_address -> TIMER_STATUS_INPUT:address
	wire         mm_interconnect_0_timer_ctrl_output_s1_chipselect;                      // mm_interconnect_0:TIMER_CTRL_OUTPUT_s1_chipselect -> TIMER_CTRL_OUTPUT:chipselect
	wire  [31:0] mm_interconnect_0_timer_ctrl_output_s1_readdata;                        // TIMER_CTRL_OUTPUT:readdata -> mm_interconnect_0:TIMER_CTRL_OUTPUT_s1_readdata
	wire   [1:0] mm_interconnect_0_timer_ctrl_output_s1_address;                         // mm_interconnect_0:TIMER_CTRL_OUTPUT_s1_address -> TIMER_CTRL_OUTPUT:address
	wire         mm_interconnect_0_timer_ctrl_output_s1_write;                           // mm_interconnect_0:TIMER_CTRL_OUTPUT_s1_write -> TIMER_CTRL_OUTPUT:write_n
	wire  [31:0] mm_interconnect_0_timer_ctrl_output_s1_writedata;                       // mm_interconnect_0:TIMER_CTRL_OUTPUT_s1_writedata -> TIMER_CTRL_OUTPUT:writedata
	wire         mm_interconnect_0_audio_timer_s1_chipselect;                            // mm_interconnect_0:AUDIO_TIMER_s1_chipselect -> AUDIO_TIMER:chipselect
	wire  [15:0] mm_interconnect_0_audio_timer_s1_readdata;                              // AUDIO_TIMER:readdata -> mm_interconnect_0:AUDIO_TIMER_s1_readdata
	wire   [2:0] mm_interconnect_0_audio_timer_s1_address;                               // mm_interconnect_0:AUDIO_TIMER_s1_address -> AUDIO_TIMER:address
	wire         mm_interconnect_0_audio_timer_s1_write;                                 // mm_interconnect_0:AUDIO_TIMER_s1_write -> AUDIO_TIMER:write_n
	wire  [15:0] mm_interconnect_0_audio_timer_s1_writedata;                             // mm_interconnect_0:AUDIO_TIMER_s1_writedata -> AUDIO_TIMER:writedata
	wire         irq_mapper_receiver0_irq;                                               // AUDIO_OUT:irq -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                                               // UART_NIOS_V:av_irq -> irq_mapper:receiver1_irq
	wire         irq_mapper_receiver2_irq;                                               // REG_BTN_INPUT:irq -> irq_mapper:receiver2_irq
	wire         irq_mapper_receiver3_irq;                                               // REG_SW_INPUT:irq -> irq_mapper:receiver3_irq
	wire         irq_mapper_receiver4_irq;                                               // AUDIO_TIMER:irq -> irq_mapper:receiver4_irq
	wire  [31:0] cpu_nios_ii_irq_irq;                                                    // irq_mapper:sender_irq -> CPU_NIOS_II:irq
	wire         rst_controller_reset_out_reset;                                         // rst_controller:reset_out -> [AUDIO_CONFIG:reset, AUDIO_OUT:reset, AUDIO_TIMER:reset_n, CPU_NIOS_II:reset_n, RAM_NIOS_V:reset, REG_BTN_INPUT:reset_n, REG_SW_INPUT:reset_n, TIMER_CTRL_OUTPUT:reset_n, TIMER_STATUS_INPUT:reset_n, UART_NIOS_V:rst_n, irq_mapper:reset, mm_interconnect_0:CPU_NIOS_II_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                                     // rst_controller:reset_req -> [CPU_NIOS_II:reset_req, RAM_NIOS_V:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                                     // rst_controller_001:reset_out -> [VGA_CHAR_BUFFER:reset, VGA_CONTROLLER:reset, mm_interconnect_0:VGA_CHAR_BUFFER_reset_reset_bridge_in_reset_reset]

	MusicPlayerPlatformDesign_AUDIO_CONFIG audio_config (
		.clk         (clk_clk),                                                           //                    clk.clk
		.reset       (rst_controller_reset_out_reset),                                    //                  reset.reset
		.address     (mm_interconnect_0_audio_config_avalon_av_config_slave_address),     // avalon_av_config_slave.address
		.byteenable  (mm_interconnect_0_audio_config_avalon_av_config_slave_byteenable),  //                       .byteenable
		.read        (mm_interconnect_0_audio_config_avalon_av_config_slave_read),        //                       .read
		.write       (mm_interconnect_0_audio_config_avalon_av_config_slave_write),       //                       .write
		.writedata   (mm_interconnect_0_audio_config_avalon_av_config_slave_writedata),   //                       .writedata
		.readdata    (mm_interconnect_0_audio_config_avalon_av_config_slave_readdata),    //                       .readdata
		.waitrequest (mm_interconnect_0_audio_config_avalon_av_config_slave_waitrequest), //                       .waitrequest
		.I2C_SDAT    (audio_config_export_SDAT),                                          //     external_interface.export
		.I2C_SCLK    (audio_config_export_SCLK)                                           //                       .export
	);

	MusicPlayerPlatformDesign_AUDIO_OUT audio_out (
		.clk         (clk_clk),                                                   //                clk.clk
		.reset       (rst_controller_reset_out_reset),                            //              reset.reset
		.address     (mm_interconnect_0_audio_out_avalon_audio_slave_address),    // avalon_audio_slave.address
		.chipselect  (mm_interconnect_0_audio_out_avalon_audio_slave_chipselect), //                   .chipselect
		.read        (mm_interconnect_0_audio_out_avalon_audio_slave_read),       //                   .read
		.write       (mm_interconnect_0_audio_out_avalon_audio_slave_write),      //                   .write
		.writedata   (mm_interconnect_0_audio_out_avalon_audio_slave_writedata),  //                   .writedata
		.readdata    (mm_interconnect_0_audio_out_avalon_audio_slave_readdata),   //                   .readdata
		.irq         (irq_mapper_receiver0_irq),                                  //          interrupt.irq
		.AUD_BCLK    (audio_export_BCLK),                                         // external_interface.export
		.AUD_DACDAT  (audio_export_DACDAT),                                       //                   .export
		.AUD_DACLRCK (audio_export_DACLRCK)                                       //                   .export
	);

	MusicPlayerPlatformDesign_AUDIO_TIMER audio_timer (
		.clk        (clk_clk),                                     //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             // reset.reset_n
		.address    (mm_interconnect_0_audio_timer_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_audio_timer_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_audio_timer_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_audio_timer_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_audio_timer_s1_write),     //      .write_n
		.irq        (irq_mapper_receiver4_irq)                     //   irq.irq
	);

	MusicPlayerPlatformDesign_CPU_NIOS_II cpu_nios_ii (
		.clk                                 (clk_clk),                                                   //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                           //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                        //                          .reset_req
		.d_address                           (cpu_nios_ii_data_master_address),                           //               data_master.address
		.d_byteenable                        (cpu_nios_ii_data_master_byteenable),                        //                          .byteenable
		.d_read                              (cpu_nios_ii_data_master_read),                              //                          .read
		.d_readdata                          (cpu_nios_ii_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (cpu_nios_ii_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (cpu_nios_ii_data_master_write),                             //                          .write
		.d_writedata                         (cpu_nios_ii_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (cpu_nios_ii_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (cpu_nios_ii_instruction_master_address),                    //        instruction_master.address
		.i_read                              (cpu_nios_ii_instruction_master_read),                       //                          .read
		.i_readdata                          (cpu_nios_ii_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (cpu_nios_ii_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (cpu_nios_ii_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (),                                                          //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                           // custom_instruction_master.readra
	);

	MusicPlayerPlatformDesign_RAM_NIOS_V ram_nios_v (
		.clk        (clk_clk),                                    //   clk1.clk
		.address    (mm_interconnect_0_ram_nios_v_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_ram_nios_v_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_ram_nios_v_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_ram_nios_v_s1_write),      //       .write
		.readdata   (mm_interconnect_0_ram_nios_v_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_ram_nios_v_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_ram_nios_v_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),             // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),         //       .reset_req
		.freeze     (1'b0)                                        // (terminated)
	);

	MusicPlayerPlatformDesign_REG_BTN_INPUT reg_btn_input (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_reg_btn_input_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_reg_btn_input_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_reg_btn_input_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_reg_btn_input_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_reg_btn_input_s1_readdata),   //                    .readdata
		.in_port    (buttons_input_export),                          // external_connection.export
		.irq        (irq_mapper_receiver2_irq)                       //                 irq.irq
	);

	MusicPlayerPlatformDesign_REG_SW_INPUT reg_sw_input (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_reg_sw_input_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_reg_sw_input_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_reg_sw_input_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_reg_sw_input_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_reg_sw_input_s1_readdata),   //                    .readdata
		.in_port    (switch_input_export),                          // external_connection.export
		.irq        (irq_mapper_receiver3_irq)                      //                 irq.irq
	);

	MusicPlayerPlatformDesign_TIMER_CTRL_OUTPUT timer_ctrl_output (
		.clk        (clk_clk),                                           //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                   //               reset.reset_n
		.address    (mm_interconnect_0_timer_ctrl_output_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_timer_ctrl_output_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_timer_ctrl_output_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_timer_ctrl_output_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_timer_ctrl_output_s1_readdata),   //                    .readdata
		.out_port   (timer_ctrl_output_export)                           // external_connection.export
	);

	MusicPlayerPlatformDesign_TIMER_STATUS_INPUT timer_status_input (
		.clk      (clk_clk),                                          //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                  //               reset.reset_n
		.address  (mm_interconnect_0_timer_status_input_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_timer_status_input_s1_readdata), //                    .readdata
		.in_port  (timer_status_input_export)                         // external_connection.export
	);

	MusicPlayerPlatformDesign_UART_NIOS_V uart_nios_v (
		.clk            (clk_clk),                                                     //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                             //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_uart_nios_v_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_uart_nios_v_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                                     //               irq.irq
	);

	MusicPlayerPlatformDesign_VGA_CHAR_BUFFER vga_char_buffer (
		.clk                  (vga_clk_clk),                                                            //                       clk.clk
		.reset                (rst_controller_001_reset_out_reset),                                     //                     reset.reset
		.ctrl_address         (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_address),    // avalon_char_control_slave.address
		.ctrl_byteenable      (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_byteenable), //                          .byteenable
		.ctrl_chipselect      (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_chipselect), //                          .chipselect
		.ctrl_read            (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_read),       //                          .read
		.ctrl_write           (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_write),      //                          .write
		.ctrl_writedata       (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_writedata),  //                          .writedata
		.ctrl_readdata        (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_readdata),   //                          .readdata
		.buf_byteenable       (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_byteenable),  //  avalon_char_buffer_slave.byteenable
		.buf_chipselect       (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_chipselect),  //                          .chipselect
		.buf_read             (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_read),        //                          .read
		.buf_write            (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_write),       //                          .write
		.buf_writedata        (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_writedata),   //                          .writedata
		.buf_readdata         (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_readdata),    //                          .readdata
		.buf_waitrequest      (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_waitrequest), //                          .waitrequest
		.buf_address          (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_address),     //                          .address
		.stream_ready         (vga_char_buffer_avalon_char_source_ready),                               //        avalon_char_source.ready
		.stream_startofpacket (vga_char_buffer_avalon_char_source_startofpacket),                       //                          .startofpacket
		.stream_endofpacket   (vga_char_buffer_avalon_char_source_endofpacket),                         //                          .endofpacket
		.stream_valid         (vga_char_buffer_avalon_char_source_valid),                               //                          .valid
		.stream_data          (vga_char_buffer_avalon_char_source_data)                                 //                          .data
	);

	MusicPlayerPlatformDesign_VGA_CONTROLLER vga_controller (
		.clk           (vga_clk_clk),                                      //                clk.clk
		.reset         (rst_controller_001_reset_out_reset),               //              reset.reset
		.data          (vga_char_buffer_avalon_char_source_data),          //    avalon_vga_sink.data
		.startofpacket (vga_char_buffer_avalon_char_source_startofpacket), //                   .startofpacket
		.endofpacket   (vga_char_buffer_avalon_char_source_endofpacket),   //                   .endofpacket
		.valid         (vga_char_buffer_avalon_char_source_valid),         //                   .valid
		.ready         (vga_char_buffer_avalon_char_source_ready),         //                   .ready
		.VGA_CLK       (vga_outputs_CLK),                                  // external_interface.export
		.VGA_HS        (vga_outputs_HS),                                   //                   .export
		.VGA_VS        (vga_outputs_VS),                                   //                   .export
		.VGA_BLANK     (vga_outputs_BLANK),                                //                   .export
		.VGA_SYNC      (vga_outputs_SYNC),                                 //                   .export
		.VGA_R         (vga_outputs_R),                                    //                   .export
		.VGA_G         (vga_outputs_G),                                    //                   .export
		.VGA_B         (vga_outputs_B)                                     //                   .export
	);

	MusicPlayerPlatformDesign_mm_interconnect_0 mm_interconnect_0 (
		.CLK_clk_clk                                          (clk_clk),                                                                //                                     CLK_clk.clk
		.VGA_CLOCK_BRIDGE_out_clk_clk                         (vga_clk_clk),                                                            //                    VGA_CLOCK_BRIDGE_out_clk.clk
		.CPU_NIOS_II_reset_reset_bridge_in_reset_reset        (rst_controller_reset_out_reset),                                         //     CPU_NIOS_II_reset_reset_bridge_in_reset.reset
		.VGA_CHAR_BUFFER_reset_reset_bridge_in_reset_reset    (rst_controller_001_reset_out_reset),                                     // VGA_CHAR_BUFFER_reset_reset_bridge_in_reset.reset
		.CPU_NIOS_II_data_master_address                      (cpu_nios_ii_data_master_address),                                        //                     CPU_NIOS_II_data_master.address
		.CPU_NIOS_II_data_master_waitrequest                  (cpu_nios_ii_data_master_waitrequest),                                    //                                            .waitrequest
		.CPU_NIOS_II_data_master_byteenable                   (cpu_nios_ii_data_master_byteenable),                                     //                                            .byteenable
		.CPU_NIOS_II_data_master_read                         (cpu_nios_ii_data_master_read),                                           //                                            .read
		.CPU_NIOS_II_data_master_readdata                     (cpu_nios_ii_data_master_readdata),                                       //                                            .readdata
		.CPU_NIOS_II_data_master_write                        (cpu_nios_ii_data_master_write),                                          //                                            .write
		.CPU_NIOS_II_data_master_writedata                    (cpu_nios_ii_data_master_writedata),                                      //                                            .writedata
		.CPU_NIOS_II_data_master_debugaccess                  (cpu_nios_ii_data_master_debugaccess),                                    //                                            .debugaccess
		.CPU_NIOS_II_instruction_master_address               (cpu_nios_ii_instruction_master_address),                                 //              CPU_NIOS_II_instruction_master.address
		.CPU_NIOS_II_instruction_master_waitrequest           (cpu_nios_ii_instruction_master_waitrequest),                             //                                            .waitrequest
		.CPU_NIOS_II_instruction_master_read                  (cpu_nios_ii_instruction_master_read),                                    //                                            .read
		.CPU_NIOS_II_instruction_master_readdata              (cpu_nios_ii_instruction_master_readdata),                                //                                            .readdata
		.AUDIO_CONFIG_avalon_av_config_slave_address          (mm_interconnect_0_audio_config_avalon_av_config_slave_address),          //         AUDIO_CONFIG_avalon_av_config_slave.address
		.AUDIO_CONFIG_avalon_av_config_slave_write            (mm_interconnect_0_audio_config_avalon_av_config_slave_write),            //                                            .write
		.AUDIO_CONFIG_avalon_av_config_slave_read             (mm_interconnect_0_audio_config_avalon_av_config_slave_read),             //                                            .read
		.AUDIO_CONFIG_avalon_av_config_slave_readdata         (mm_interconnect_0_audio_config_avalon_av_config_slave_readdata),         //                                            .readdata
		.AUDIO_CONFIG_avalon_av_config_slave_writedata        (mm_interconnect_0_audio_config_avalon_av_config_slave_writedata),        //                                            .writedata
		.AUDIO_CONFIG_avalon_av_config_slave_byteenable       (mm_interconnect_0_audio_config_avalon_av_config_slave_byteenable),       //                                            .byteenable
		.AUDIO_CONFIG_avalon_av_config_slave_waitrequest      (mm_interconnect_0_audio_config_avalon_av_config_slave_waitrequest),      //                                            .waitrequest
		.AUDIO_OUT_avalon_audio_slave_address                 (mm_interconnect_0_audio_out_avalon_audio_slave_address),                 //                AUDIO_OUT_avalon_audio_slave.address
		.AUDIO_OUT_avalon_audio_slave_write                   (mm_interconnect_0_audio_out_avalon_audio_slave_write),                   //                                            .write
		.AUDIO_OUT_avalon_audio_slave_read                    (mm_interconnect_0_audio_out_avalon_audio_slave_read),                    //                                            .read
		.AUDIO_OUT_avalon_audio_slave_readdata                (mm_interconnect_0_audio_out_avalon_audio_slave_readdata),                //                                            .readdata
		.AUDIO_OUT_avalon_audio_slave_writedata               (mm_interconnect_0_audio_out_avalon_audio_slave_writedata),               //                                            .writedata
		.AUDIO_OUT_avalon_audio_slave_chipselect              (mm_interconnect_0_audio_out_avalon_audio_slave_chipselect),              //                                            .chipselect
		.AUDIO_TIMER_s1_address                               (mm_interconnect_0_audio_timer_s1_address),                               //                              AUDIO_TIMER_s1.address
		.AUDIO_TIMER_s1_write                                 (mm_interconnect_0_audio_timer_s1_write),                                 //                                            .write
		.AUDIO_TIMER_s1_readdata                              (mm_interconnect_0_audio_timer_s1_readdata),                              //                                            .readdata
		.AUDIO_TIMER_s1_writedata                             (mm_interconnect_0_audio_timer_s1_writedata),                             //                                            .writedata
		.AUDIO_TIMER_s1_chipselect                            (mm_interconnect_0_audio_timer_s1_chipselect),                            //                                            .chipselect
		.CPU_NIOS_II_debug_mem_slave_address                  (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_address),                  //                 CPU_NIOS_II_debug_mem_slave.address
		.CPU_NIOS_II_debug_mem_slave_write                    (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_write),                    //                                            .write
		.CPU_NIOS_II_debug_mem_slave_read                     (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_read),                     //                                            .read
		.CPU_NIOS_II_debug_mem_slave_readdata                 (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_readdata),                 //                                            .readdata
		.CPU_NIOS_II_debug_mem_slave_writedata                (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_writedata),                //                                            .writedata
		.CPU_NIOS_II_debug_mem_slave_byteenable               (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_byteenable),               //                                            .byteenable
		.CPU_NIOS_II_debug_mem_slave_waitrequest              (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_waitrequest),              //                                            .waitrequest
		.CPU_NIOS_II_debug_mem_slave_debugaccess              (mm_interconnect_0_cpu_nios_ii_debug_mem_slave_debugaccess),              //                                            .debugaccess
		.RAM_NIOS_V_s1_address                                (mm_interconnect_0_ram_nios_v_s1_address),                                //                               RAM_NIOS_V_s1.address
		.RAM_NIOS_V_s1_write                                  (mm_interconnect_0_ram_nios_v_s1_write),                                  //                                            .write
		.RAM_NIOS_V_s1_readdata                               (mm_interconnect_0_ram_nios_v_s1_readdata),                               //                                            .readdata
		.RAM_NIOS_V_s1_writedata                              (mm_interconnect_0_ram_nios_v_s1_writedata),                              //                                            .writedata
		.RAM_NIOS_V_s1_byteenable                             (mm_interconnect_0_ram_nios_v_s1_byteenable),                             //                                            .byteenable
		.RAM_NIOS_V_s1_chipselect                             (mm_interconnect_0_ram_nios_v_s1_chipselect),                             //                                            .chipselect
		.RAM_NIOS_V_s1_clken                                  (mm_interconnect_0_ram_nios_v_s1_clken),                                  //                                            .clken
		.REG_BTN_INPUT_s1_address                             (mm_interconnect_0_reg_btn_input_s1_address),                             //                            REG_BTN_INPUT_s1.address
		.REG_BTN_INPUT_s1_write                               (mm_interconnect_0_reg_btn_input_s1_write),                               //                                            .write
		.REG_BTN_INPUT_s1_readdata                            (mm_interconnect_0_reg_btn_input_s1_readdata),                            //                                            .readdata
		.REG_BTN_INPUT_s1_writedata                           (mm_interconnect_0_reg_btn_input_s1_writedata),                           //                                            .writedata
		.REG_BTN_INPUT_s1_chipselect                          (mm_interconnect_0_reg_btn_input_s1_chipselect),                          //                                            .chipselect
		.REG_SW_INPUT_s1_address                              (mm_interconnect_0_reg_sw_input_s1_address),                              //                             REG_SW_INPUT_s1.address
		.REG_SW_INPUT_s1_write                                (mm_interconnect_0_reg_sw_input_s1_write),                                //                                            .write
		.REG_SW_INPUT_s1_readdata                             (mm_interconnect_0_reg_sw_input_s1_readdata),                             //                                            .readdata
		.REG_SW_INPUT_s1_writedata                            (mm_interconnect_0_reg_sw_input_s1_writedata),                            //                                            .writedata
		.REG_SW_INPUT_s1_chipselect                           (mm_interconnect_0_reg_sw_input_s1_chipselect),                           //                                            .chipselect
		.TIMER_CTRL_OUTPUT_s1_address                         (mm_interconnect_0_timer_ctrl_output_s1_address),                         //                        TIMER_CTRL_OUTPUT_s1.address
		.TIMER_CTRL_OUTPUT_s1_write                           (mm_interconnect_0_timer_ctrl_output_s1_write),                           //                                            .write
		.TIMER_CTRL_OUTPUT_s1_readdata                        (mm_interconnect_0_timer_ctrl_output_s1_readdata),                        //                                            .readdata
		.TIMER_CTRL_OUTPUT_s1_writedata                       (mm_interconnect_0_timer_ctrl_output_s1_writedata),                       //                                            .writedata
		.TIMER_CTRL_OUTPUT_s1_chipselect                      (mm_interconnect_0_timer_ctrl_output_s1_chipselect),                      //                                            .chipselect
		.TIMER_STATUS_INPUT_s1_address                        (mm_interconnect_0_timer_status_input_s1_address),                        //                       TIMER_STATUS_INPUT_s1.address
		.TIMER_STATUS_INPUT_s1_readdata                       (mm_interconnect_0_timer_status_input_s1_readdata),                       //                                            .readdata
		.UART_NIOS_V_avalon_jtag_slave_address                (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_address),                //               UART_NIOS_V_avalon_jtag_slave.address
		.UART_NIOS_V_avalon_jtag_slave_write                  (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_write),                  //                                            .write
		.UART_NIOS_V_avalon_jtag_slave_read                   (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_read),                   //                                            .read
		.UART_NIOS_V_avalon_jtag_slave_readdata               (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_readdata),               //                                            .readdata
		.UART_NIOS_V_avalon_jtag_slave_writedata              (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_writedata),              //                                            .writedata
		.UART_NIOS_V_avalon_jtag_slave_waitrequest            (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_waitrequest),            //                                            .waitrequest
		.UART_NIOS_V_avalon_jtag_slave_chipselect             (mm_interconnect_0_uart_nios_v_avalon_jtag_slave_chipselect),             //                                            .chipselect
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_address     (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_address),     //    VGA_CHAR_BUFFER_avalon_char_buffer_slave.address
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_write       (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_write),       //                                            .write
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_read        (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_read),        //                                            .read
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_readdata    (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_readdata),    //                                            .readdata
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_writedata   (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_writedata),   //                                            .writedata
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_byteenable  (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_byteenable),  //                                            .byteenable
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_waitrequest (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_waitrequest), //                                            .waitrequest
		.VGA_CHAR_BUFFER_avalon_char_buffer_slave_chipselect  (mm_interconnect_0_vga_char_buffer_avalon_char_buffer_slave_chipselect),  //                                            .chipselect
		.VGA_CHAR_BUFFER_avalon_char_control_slave_address    (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_address),    //   VGA_CHAR_BUFFER_avalon_char_control_slave.address
		.VGA_CHAR_BUFFER_avalon_char_control_slave_write      (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_write),      //                                            .write
		.VGA_CHAR_BUFFER_avalon_char_control_slave_read       (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_read),       //                                            .read
		.VGA_CHAR_BUFFER_avalon_char_control_slave_readdata   (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_readdata),   //                                            .readdata
		.VGA_CHAR_BUFFER_avalon_char_control_slave_writedata  (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_writedata),  //                                            .writedata
		.VGA_CHAR_BUFFER_avalon_char_control_slave_byteenable (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_byteenable), //                                            .byteenable
		.VGA_CHAR_BUFFER_avalon_char_control_slave_chipselect (mm_interconnect_0_vga_char_buffer_avalon_char_control_slave_chipselect)  //                                            .chipselect
	);

	MusicPlayerPlatformDesign_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.receiver2_irq (irq_mapper_receiver2_irq),       // receiver2.irq
		.receiver3_irq (irq_mapper_receiver3_irq),       // receiver3.irq
		.receiver4_irq (irq_mapper_receiver4_irq),       // receiver4.irq
		.sender_irq    (cpu_nios_ii_irq_irq)             //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (vga_clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
