#ifndef HW_MAP_H
#define HW_MAP_H

/* ======================================================================
 *  hw_map.h  --  Single source of truth for the platform's address map.
 *
 *  These bases come from the Platform Designer system "MusicPlayerPlatform-
 *  Design" (HPS_ARM.h2f_lw_axi_master path). If you re-generate the system
 *  in Qsys/Platform Designer, update ONLY this file -- nothing else in the
 *  project hardcodes an address.
 *
 *  NOTE: system.h (generated by the BSP) also defines *_BASE / *_NAME macros.
 *  Where a HAL driver is used (audio, av_config, char buffer) we prefer the
 *  generated system.h names. Where we touch raw registers (timer, buttons,
 *  switch, shared RAM) we use the explicit addresses below so the project is
 *  self-contained and reviewable against the memory-map screenshot.
 * ====================================================================== */

#include <stdint.h>

/* ---- Convenience cast helpers ------------------------------------------ */
#define REG32(addr)   (*(volatile uint32_t *)(addr))
#define REG8(addr)    (*(volatile uint8_t  *)(addr))
#define PTR32(addr)   ((volatile uint32_t *)(addr))

/* ======================================================================
 *  Peripheral base addresses (from the memory-map table)
 * ====================================================================== */

/* Audio + AV config (HAL drivers open these by NAME from system.h, but we
   keep the bases here for the status-poll trick used during init). */
#define AUDIO_CONFIG_BASE_ADDR   0x00083040u
#define AUDIO_OUT_BASE_ADDR      0x00083050u

/* Shared RAM region used for HPS <-> NIOS II data exchange.
   The intercommunication protocol itself is implemented by the partner;
   we only define the layout (see shared_mem.h) and place it here. */
#define SHARED_RAM_BASE_ADDR     0x00040000u
#define SHARED_RAM_END_ADDR      0x00080000u   /* 0x4_0000..0x7_FFFF inclusive */
#define SHARED_RAM_SIZE_BYTES    (SHARED_RAM_END_ADDR - SHARED_RAM_BASE_ADDR)

/* Custom register-mapped I/O.
   These bases are also defined by the BSP-generated system.h. We guard each
   with #ifndef so system.h's definition wins when present (avoiding redefine
   warnings) and ours only fills in if system.h didn't provide it. */
#ifndef REG_BTN_INPUT_BASE
#define REG_BTN_INPUT_BASE       0x00083030u   /* 4 push buttons, edge-capture PIO */
#endif
#ifndef REG_SW_INPUT_BASE
#define REG_SW_INPUT_BASE        0x00083020u   /* system reset switch              */
#endif
#ifndef TIMER_CTRL_OUTPUT_BASE
#define TIMER_CTRL_OUTPUT_BASE   0x00083000u   /* 2-bit timer control word out     */
#endif
#ifndef TIMER_STATUS_INPUT_BASE
#define TIMER_STATUS_INPUT_BASE  0x00083010u   /* 2-bit timer status word in       */
#endif

/* VGA character buffer. The control slave (clear/resolution) and the
   character slave (the framebuffer of ASCII codes) live at separate bases. */
#define VGA_CHAR_CTRL_BASE       0x00083068u   /* avalon_char_control_slave */
#define VGA_CHAR_BUF_BASE        0x00080000u   /* avalon_char_slave (80x60)  */

/* JTAG UART (UART_NIOS_II). Used by debug_uart.c for non-blocking prints.
   +0x0 = data (bit15 RVALID, bits7..0 data); +0x4 = control (bits31..16 = WSPACE). */
#define JTAG_UART_BASE_ADDR      0x00083060u
#define JTAG_UART_DATA_OFF       0x0u
#define JTAG_UART_CTRL_OFF       0x4u

/* ======================================================================
 *  Altera PIO register offsets (standard parallel I/O core)
 *    +0x0 data, +0x4 direction, +0x8 interruptmask, +0xC edgecapture
 * ====================================================================== */
#define PIO_DATA_OFF        0x0u
#define PIO_DIRECTION_OFF   0x4u
#define PIO_IRQ_MASK_OFF    0x8u
#define PIO_EDGECAP_OFF     0xCu

/* ======================================================================
 *  Interrupt numbers (IRQ lines on the NIOS II internal interrupt ctrl).
 *  These MUST match the "IRQ" column you set in Platform Designer for each
 *  component's interrupt connection. Adjust to your generated system.h
 *  (look for *_IRQ defines) if they differ.
 * ====================================================================== */
#ifndef BTN_PIO_IRQ
#define BTN_PIO_IRQ         1   /* REG_BTN_INPUT  */
#endif
#ifndef RST_SW_IRQ
#define RST_SW_IRQ          2   /* REG_SW_INPUT (reset switch)               */
#endif
#ifndef AUDIO_OUT_IRQ
#define AUDIO_OUT_IRQ       3   /* AUDIO_OUT write interrupt                 */
#endif

/* ======================================================================
 *  Timer control / status encoding (timer_ctrl_wire / timer_status_wire)
 *    00 = do-nothing (latches whatever functional state is active)
 *    01 = running
 *    10 = pause
 *    11 = reset
 *  We always issue a command, wait for status to mirror it, then return to
 *  DONOTHING so a transient bus glitch can't re-trigger an unwanted state.
 * ====================================================================== */
typedef enum {
    TIMER_CMD_NOP    = 0x0,   /* 00 */
    TIMER_CMD_RUN    = 0x1,   /* 01 */
    TIMER_CMD_PAUSE  = 0x2,   /* 10 */
    TIMER_CMD_RESET  = 0x3    /* 11 */
} timer_cmd_t;

/* ======================================================================
 *  VGA geometry (on-board VGA DAC -> 80 x 60 character grid)
 * ====================================================================== */
#define VGA_COLS            80
#define VGA_ROWS            60
#define VGA_CTRL_REG        0     /* word index into control slave */
#define VGA_RESOL_REG       1
#define VGA_CLEAR_BIT       (1u << 16)
#define VGA_RESET_GUARD_US  200000

/* ======================================================================
 *  Audio configuration constants
 *
 *  The WM8731 CODEC drains the output FIFO at a single fixed hardware sample
 *  rate (CODEC_HW_RATE), set by the AV-config "Sampling Rate" and the Audio
 *  Clock IP's MCLK. We do NOT reconfigure the CODEC on the fly; instead we
 *  honour a song's logical rate by *replicating* each frame
 *  (CODEC_HW_RATE / logical_rate) times when pushing it to the FIFO.
 *
 *  Set the AV-config "Sampling Rate" to 48 kHz, Bit Length = 16, Data Format
 *  = Left Justified, board = DE1-SoC. The audio core's Data Width is also 16.
 *  So CODEC_HW_RATE must be 48000.
 *
 *  Why 48 kHz and not 96 kHz: all source content is 48 kHz or below (44.1 kHz
 *  is resampled to 48 kHz on the HPS before the NIOS sees it), so 96 kHz would
 *  carry no extra information -- it would only double the FIFO write rate and
 *  the interrupt load for nothing. 48 kHz halves the CPU's streaming work and
 *  lets a 48 kHz song play 1:1 with no replication.
 *
 *  Clean divisors of 48 kHz:
 *      48000 / 8000  = 6    (8 kHz  song -> repeat each frame 6x)
 *      48000 / 16000 = 3    (16 kHz song -> repeat 3x)
 *      48000 / 48000 = 1    (48 kHz song -> 1:1, no replication)
 *  NON-integer (cannot be done by replication alone):
 *      48000 / 44100 = 1.088...  -> 44.1 kHz must be resampled UPSTREAM
 *      (on the HPS) to 48 kHz before it reaches the NIOS. The NIOS engine
 *      assumes integer divisors.
 * ====================================================================== */
#define CODEC_HW_RATE       48000u   /* MUST match AV-config "Sampling Rate" */
#define CODEC_BIT_LENGTH    16u      /* AV-config Bit Length / core DataWidth */

#define AUDIO_AIS_BIT       (1u << 8) /* status reg bit: auto-init complete   */
#define AUDIO_STATUS_OFF    0x4u      /* AV-config status reg byte offset     */

/* ======================================================================
 *  Application tunables
 * ====================================================================== */
#define HARDCODED_SONG_SECONDS  25u   /* display + dummy-buffer length        */
#define DUMMY_SONG_COUNT        10u   /* HPS "reports" this many songs        */
#define MAX_SONGS               32u   /* upper bound for the song table       */

/* Metadata string caps (must fit on the VGA line; see vga_ui.c). */
#define META_NAME_LEN   40
#define META_ART_LEN    40
#define META_ALB_LEN    40
#define META_DUR_LEN    8     /* "MM:SS" + nul */

#endif /* HW_MAP_H */