# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-de1soc-fpga"
BBFILE_PATTERN_meta-de1soc-fpga = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-de1soc-fpga = "6"

LAYERDEPENDS_meta-de1soc-fpga = "core"
LAYERSERIES_COMPAT_meta-de1soc-fpga = "scarthgap"
