	MusicPlayerPlatformDesign u0 (
		.audio_clk_export_clk              (<connected-to-audio_clk_export_clk>),              //       audio_clk_export.clk
		.audio_config_export_SDAT          (<connected-to-audio_config_export_SDAT>),          //    audio_config_export.SDAT
		.audio_config_export_SCLK          (<connected-to-audio_config_export_SCLK>),          //                       .SCLK
		.audio_export_BCLK                 (<connected-to-audio_export_BCLK>),                 //           audio_export.BCLK
		.audio_export_DACDAT               (<connected-to-audio_export_DACDAT>),               //                       .DACDAT
		.audio_export_DACLRCK              (<connected-to-audio_export_DACLRCK>),              //                       .DACLRCK
		.buttons_input_export              (<connected-to-buttons_input_export>),              //          buttons_input.export
		.clk_clk                           (<connected-to-clk_clk>),                           //                    clk.clk
		.filter_select_filter_sw           (<connected-to-filter_select_filter_sw>),           //          filter_select.filter_sw
		.hps_arm_h2f_mpu_events_eventi     (<connected-to-hps_arm_h2f_mpu_events_eventi>),     // hps_arm_h2f_mpu_events.eventi
		.hps_arm_h2f_mpu_events_evento     (<connected-to-hps_arm_h2f_mpu_events_evento>),     //                       .evento
		.hps_arm_h2f_mpu_events_standbywfe (<connected-to-hps_arm_h2f_mpu_events_standbywfe>), //                       .standbywfe
		.hps_arm_h2f_mpu_events_standbywfi (<connected-to-hps_arm_h2f_mpu_events_standbywfi>), //                       .standbywfi
		.hps_io_hps_io_emac0_inst_TX_CLK   (<connected-to-hps_io_hps_io_emac0_inst_TX_CLK>),   //                 hps_io.hps_io_emac0_inst_TX_CLK
		.hps_io_hps_io_emac0_inst_TXD0     (<connected-to-hps_io_hps_io_emac0_inst_TXD0>),     //                       .hps_io_emac0_inst_TXD0
		.hps_io_hps_io_emac0_inst_TXD1     (<connected-to-hps_io_hps_io_emac0_inst_TXD1>),     //                       .hps_io_emac0_inst_TXD1
		.hps_io_hps_io_emac0_inst_TXD2     (<connected-to-hps_io_hps_io_emac0_inst_TXD2>),     //                       .hps_io_emac0_inst_TXD2
		.hps_io_hps_io_emac0_inst_TXD3     (<connected-to-hps_io_hps_io_emac0_inst_TXD3>),     //                       .hps_io_emac0_inst_TXD3
		.hps_io_hps_io_emac0_inst_RXD0     (<connected-to-hps_io_hps_io_emac0_inst_RXD0>),     //                       .hps_io_emac0_inst_RXD0
		.hps_io_hps_io_emac0_inst_MDIO     (<connected-to-hps_io_hps_io_emac0_inst_MDIO>),     //                       .hps_io_emac0_inst_MDIO
		.hps_io_hps_io_emac0_inst_MDC      (<connected-to-hps_io_hps_io_emac0_inst_MDC>),      //                       .hps_io_emac0_inst_MDC
		.hps_io_hps_io_emac0_inst_RX_CTL   (<connected-to-hps_io_hps_io_emac0_inst_RX_CTL>),   //                       .hps_io_emac0_inst_RX_CTL
		.hps_io_hps_io_emac0_inst_TX_CTL   (<connected-to-hps_io_hps_io_emac0_inst_TX_CTL>),   //                       .hps_io_emac0_inst_TX_CTL
		.hps_io_hps_io_emac0_inst_RX_CLK   (<connected-to-hps_io_hps_io_emac0_inst_RX_CLK>),   //                       .hps_io_emac0_inst_RX_CLK
		.hps_io_hps_io_emac0_inst_RXD1     (<connected-to-hps_io_hps_io_emac0_inst_RXD1>),     //                       .hps_io_emac0_inst_RXD1
		.hps_io_hps_io_emac0_inst_RXD2     (<connected-to-hps_io_hps_io_emac0_inst_RXD2>),     //                       .hps_io_emac0_inst_RXD2
		.hps_io_hps_io_emac0_inst_RXD3     (<connected-to-hps_io_hps_io_emac0_inst_RXD3>),     //                       .hps_io_emac0_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD       (<connected-to-hps_io_hps_io_sdio_inst_CMD>),       //                       .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0        (<connected-to-hps_io_hps_io_sdio_inst_D0>),        //                       .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1        (<connected-to-hps_io_hps_io_sdio_inst_D1>),        //                       .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK       (<connected-to-hps_io_hps_io_sdio_inst_CLK>),       //                       .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2        (<connected-to-hps_io_hps_io_sdio_inst_D2>),        //                       .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3        (<connected-to-hps_io_hps_io_sdio_inst_D3>),        //                       .hps_io_sdio_inst_D3
		.memory_mem_a                      (<connected-to-memory_mem_a>),                      //                 memory.mem_a
		.memory_mem_ba                     (<connected-to-memory_mem_ba>),                     //                       .mem_ba
		.memory_mem_ck                     (<connected-to-memory_mem_ck>),                     //                       .mem_ck
		.memory_mem_ck_n                   (<connected-to-memory_mem_ck_n>),                   //                       .mem_ck_n
		.memory_mem_cke                    (<connected-to-memory_mem_cke>),                    //                       .mem_cke
		.memory_mem_cs_n                   (<connected-to-memory_mem_cs_n>),                   //                       .mem_cs_n
		.memory_mem_ras_n                  (<connected-to-memory_mem_ras_n>),                  //                       .mem_ras_n
		.memory_mem_cas_n                  (<connected-to-memory_mem_cas_n>),                  //                       .mem_cas_n
		.memory_mem_we_n                   (<connected-to-memory_mem_we_n>),                   //                       .mem_we_n
		.memory_mem_reset_n                (<connected-to-memory_mem_reset_n>),                //                       .mem_reset_n
		.memory_mem_dq                     (<connected-to-memory_mem_dq>),                     //                       .mem_dq
		.memory_mem_dqs                    (<connected-to-memory_mem_dqs>),                    //                       .mem_dqs
		.memory_mem_dqs_n                  (<connected-to-memory_mem_dqs_n>),                  //                       .mem_dqs_n
		.memory_mem_odt                    (<connected-to-memory_mem_odt>),                    //                       .mem_odt
		.memory_mem_dm                     (<connected-to-memory_mem_dm>),                     //                       .mem_dm
		.memory_oct_rzqin                  (<connected-to-memory_oct_rzqin>),                  //                       .oct_rzqin
		.reset_reset_n                     (<connected-to-reset_reset_n>),                     //                  reset.reset_n
		.switch_input_export               (<connected-to-switch_input_export>),               //           switch_input.export
		.timer_ctrl_output_export          (<connected-to-timer_ctrl_output_export>),          //      timer_ctrl_output.export
		.timer_status_input_export         (<connected-to-timer_status_input_export>),         //     timer_status_input.export
		.vga_clk_clk                       (<connected-to-vga_clk_clk>),                       //                vga_clk.clk
		.vga_outputs_CLK                   (<connected-to-vga_outputs_CLK>),                   //            vga_outputs.CLK
		.vga_outputs_HS                    (<connected-to-vga_outputs_HS>),                    //                       .HS
		.vga_outputs_VS                    (<connected-to-vga_outputs_VS>),                    //                       .VS
		.vga_outputs_BLANK                 (<connected-to-vga_outputs_BLANK>),                 //                       .BLANK
		.vga_outputs_SYNC                  (<connected-to-vga_outputs_SYNC>),                  //                       .SYNC
		.vga_outputs_R                     (<connected-to-vga_outputs_R>),                     //                       .R
		.vga_outputs_G                     (<connected-to-vga_outputs_G>),                     //                       .G
		.vga_outputs_B                     (<connected-to-vga_outputs_B>)                      //                       .B
	);

