# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/adriel/poky-scarthgap-5.0.15/meta \
  /home/adriel/poky-scarthgap-5.0.15/meta-poky \
  /home/adriel/poky-scarthgap-5.0.15/meta-yocto-bsp \
  /home/adriel/poky-scarthgap-5.0.15/meta-raspberrypi \
  /home/adriel/poky-scarthgap-5.0.15/meta-rpi4-config \
  /home/adriel/poky-scarthgap-5.0.15/meta-robot \
  "
